/* integrad-dashboard/src/styles/caseload.styles.ts */

import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  page: {
    padding: 20,
    background: "#f8fafc",
    minHeight: "100%",
    boxSizing: "border-box",
  },
  shell: {
    display: "flex",
    flexDirection: "column",
    gap: 18,
    maxWidth: 1600,
    margin: "0 auto",
  },
  header: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    padding: "4px 2px 0 2px",
  },
  headerContent: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    minWidth: 0,
  },
  eyebrow: {
    fontSize: 12,
    lineHeight: 1.4,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "#64748b",
  },
  title: {
    margin: 0,
    fontSize: 24,
    lineHeight: 1.2,
    fontWeight: 700,
    color: "#0f172a",
  },
  description: {
    margin: 0,
    fontSize: 14,
    lineHeight: 1.6,
    color: "#475569",
    maxWidth: 760,
  },
  surface: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 18,
    boxShadow: "0 8px 24px rgba(15, 23, 42, 0.06)",
    padding: 16,
  },
  filtersBar: {
    display: "flex",
    gap: 12,
    marginBottom: 16,
    flexWrap: "wrap",
  },
  filterSelect: {
    padding: "8px 10px",
    borderRadius: 10,
    border: "1px solid #cbd5e1",
    backgroundColor: "#ffffff",
    color: "#0f172a",
    fontSize: 13,
    fontWeight: 600,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  th: {
    padding: "0 0 12px 0",
    fontSize: 12,
    color: "#64748b",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  tr: {
    borderTop: "1px solid #e5e7eb",
  },
  td: {
    padding: "14px 8px 14px 0",
    verticalAlign: "top",
  },
  patientCard: {
    marginBottom: 0,
    padding: 0,
    boxShadow: "none",
    border: "none",
    background: "transparent",
  },
  patientCell: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    minWidth: 0,
  },
  patientMeta: {
    minWidth: 0,
  },
  patientName: {
    fontWeight: 700,
    color: "#111827",
    lineHeight: 1.3,
  },
  patientSecondary: {
    fontSize: 12,
    color: "#6b7280",
    marginTop: 4,
  },
  priorityPill: {
    color: "#ffffff",
    padding: "4px 10px",
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 700,
    display: "inline-block",
    whiteSpace: "nowrap",
  },
  priorityHumanLabel: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: 600,
    color: "#334155",
  },
  reasonText: {
    fontSize: 13,
    color: "#374151",
    lineHeight: 1.5,
    maxWidth: 420,
  },
  badgesWrap: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
  },
  sourceBadge: {
    fontSize: 12,
    padding: "4px 8px",
    borderRadius: 999,
    background: "#f3f4f6",
    color: "#374151",
    fontWeight: 600,
  },
  inProgressBox: {
    display: "inline-block",
    background: "#fff7ed",
    border: "1px solid #fed7aa",
    color: "#9a3412",
    borderRadius: 12,
    padding: "8px 10px",
    fontSize: 12,
    fontWeight: 700,
    lineHeight: 1.4,
  },
  availableText: {
    fontSize: 13,
    color: "#166534",
    fontWeight: 600,
  },
  managementMetaText: {
    marginTop: 6,
    fontSize: 12,
    color: "#6b7280",
  },
  actionsWrap: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  infoText: {
    fontSize: 14,
    color: "#6b7280",
    padding: "8px 4px",
  },
  errorBox: {
    color: "#991b1b",
    background: "#fef2f2",
    border: "1px solid #fecaca",
    borderRadius: 12,
    padding: "10px 12px",
    marginBottom: 8,
    fontWeight: 600,
  },
  paginationBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 16,
    padding: "16px 0 0 0",
    flexWrap: "wrap",
  },
  pageSizeGroup: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  paginationLabel: {
    fontSize: 13,
    color: "#475569",
    fontWeight: 500,
  },
  paginationControls: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  },
  paginationInfo: {
    fontSize: 13,
    color: "#334155",
    fontWeight: 600,
    minWidth: 72,
    textAlign: "center",
  },
  paginationButton: {
    border: "1px solid #cbd5e1",
    backgroundColor: "#ffffff",
    color: "#0f172a",
    borderRadius: 10,
    padding: "8px 12px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
};

export const btnPrimary: CSSProperties = {
  padding: "8px 12px",
  borderRadius: 999,
  border: "1px solid rgba(47, 66, 173, 1)",
  background: "var(--color-primary, #2f42ad)",
  color: "#ffffff",
  fontWeight: 600,
  cursor: "pointer",
};

export const btnSecondary: CSSProperties = {
  padding: "8px 12px",
  borderRadius: 999,
  border: "1px solid #d1d5db",
  background: "#ffffff",
  color: "#374151",
  fontWeight: 600,
  cursor: "pointer",
};
